### PR TITLE
docs: add markdown table output for served files

### PR DESCRIPTION
**Pull request by erikmejias**

### CODE REVIEW

**Comment by erikmejias** [comment]
@alexiglesias93 the output looks something like this:
image

Makes it easier to copy/paste the scripts into Webflow + for documentation purposes.

**Comment by alexiglesias93** [comment]
@erikmejias I like the idea but the layout breaks when the script sources have different lengths:
image

Perhaps we could use an alternative to a markdown table?

**Comment by erikmejias** [comment]
`console.table()` might solve that, I just don't like the index column being shown.
But that might work better.

**Comment by alexiglesias93** [comment]
Yeah, definetely looks cleaner with `console.table`.

image

**Comment by alexiglesias93** [comment]
Can be even made prettier:

image

image

**Comment by erikmejias** [comment]
Yeah, I've had this exact version before 😅 
If you like it please merge it.

**Review by alexiglesias93 — APPROVED** [review]
Reworked the code, output looks like this:

image

**Pull request merged**
